### ISSUE TITLE
[Bug report] Getting error while building the application.

### ISSUE THREAD

**Issue by AlfaizCeras** [fluttercandies/extended_image#605] opened 2023-08-17 10:40 UTC
### Version

8.0.2

### Platforms

Android, iOS

### Device Model

Google Pixel 6(Android 13)

### flutter info

```sh
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale
    en-IN)
    • Flutter version 3.13.0 on channel stable at /Users/alfaiz/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (33 hours ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/alfaiz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/alfaiz/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/alfaiz/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.1.4)
    • IntelliJ at /Users/alfaiz/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9225.16/IntelliJ IDEA
      CE.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Users/alfaiz/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/232.8660.185/IntelliJ IDEA
      CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### How to reproduce?

Getting error while building the application.

### Logs

```sh
Note: Recompile with -Xlint:unchecked for details.
../../../.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/extended_image.dart:976:36: Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
 - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('../../../SDK/flutter/packages/flutter/lib/src/painting/border_radius.dart').
 - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('../../../SDK/flutter/packages/flutter/lib/src/painting/border_radius.dart').
              borderRadius: widget.borderRadius,
                                   ^
../../../.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:202:13: Error: 'ImageTilingInfo' isn't a type.
      final ImageTilingInfo info =
            ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:203:11: Error: Method not found: 'createTilingInfo'.
          createTilingInfo(repeat, rect, destinationRect, sourceRect);
          ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
```

**Comment by AlexV525** [comment] 2023-08-17 11:03
Duplicate of #602

**Closed by AlexV525** 2023-08-17 11:03 UTC

**Comment by tuandungnguyen** [comment] 2023-08-25 07:56
![image](https://github.com/fluttercandies/extended_image/assets/17266479/4a3c7dad-adf1-4c1a-9ebe-56731f2af67a)

There is a new issue after upgrading to v8.1.0
 extended_image: ^8.1.0
 
 Please support

**Comment by pablo-johnson** [comment] 2023-10-04 21:35
same problem here
